# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toolsMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

from PyQt5 import QtCore, QtGui, QtWidgets
sys.path.insert(1, 'C:/Users/Jung-WeiLiao/OneDrive - Durham Magneto Optics Ltd/Document/Qt/TemperatureProgramHotPlate/GUI/Conditions')
from ui_Conditions import formConditions


class Ui_FormToolsMenu(object):
    def setupUi(self, FormToolsMenu):
        FormToolsMenu.setObjectName("FormToolsMenu")
        FormToolsMenu.resize(268, 416)
        self.centralwidget = QtWidgets.QWidget(FormToolsMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.pushBtnBakingConditions = QtWidgets.QPushButton(self.centralwidget, clicked=lambda:self.button_Clicked("Conditions"))
        self.pushBtnBakingConditions.setGeometry(QtCore.QRect(20, 20, 211, 101))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        self.pushBtnBakingConditions.setFont(font)
        self.pushBtnBakingConditions.setObjectName("pushBtnBakingConditions")
        self.pushBtnBaking = QtWidgets.QPushButton(self.centralwidget)
        self.pushBtnBaking.setGeometry(QtCore.QRect(20, 130, 211, 101))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        self.pushBtnBaking.setFont(font)
        self.pushBtnBaking.setObjectName("pushBtnBaking")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 240, 211, 121))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 70, 191, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_currentT = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_currentT.setFont(font)
        self.label_currentT.setObjectName("label_currentT")
        self.horizontalLayout.addWidget(self.label_currentT)
        self.label_currentStat = QtWidgets.QLabel(self.groupBox)
        self.label_currentStat.setGeometry(QtCore.QRect(10, 30, 161, 31))
        self.label_currentStat.setObjectName("label_currentStat")
        self.groupBox.raise_()
        self.pushBtnBakingConditions.raise_()
        self.pushBtnBaking.raise_()
        FormToolsMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FormToolsMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 268, 22))
        self.menubar.setObjectName("menubar")
        FormToolsMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FormToolsMenu)
        self.statusbar.setObjectName("statusbar")
        FormToolsMenu.setStatusBar(self.statusbar)

        self.retranslateUi(FormToolsMenu)
        QtCore.QMetaObject.connectSlotsByName(FormToolsMenu)

        self.formConditions = formConditions()

    def retranslateUi(self, FormToolsMenu):
        _translate = QtCore.QCoreApplication.translate
        FormToolsMenu.setWindowTitle(_translate("FormToolsMenu", "Tools Menu"))
        self.pushBtnBakingConditions.setText(_translate("FormToolsMenu", "Conditions"))
        self.pushBtnBaking.setText(_translate("FormToolsMenu", "Baking"))
        self.groupBox.setTitle(_translate("FormToolsMenu", "Status"))
        self.label.setText(_translate("FormToolsMenu", "Current T:"))
        self.label_currentT.setText(_translate("FormToolsMenu", "Waiting..."))
        self.label_currentStat.setText(_translate("FormToolsMenu", "Standby..."))
    
    def button_Clicked(self, strClickedButton):
        if strClickedButton == "Conditions":
            self.formConditions.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormToolsMenu = QtWidgets.QMainWindow()
    ui = Ui_FormToolsMenu()
    ui.setupUi(FormToolsMenu)
    FormToolsMenu.show()
    sys.exit(app.exec_())
