# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(800, 600)
        self.gBoxCurrentTemperature = QtWidgets.QGroupBox(Widget)
        self.gBoxCurrentTemperature.setGeometry(QtCore.QRect(20, 30, 331, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.gBoxCurrentTemperature.setFont(font)
        self.gBoxCurrentTemperature.setObjectName("gBoxCurrentTemperature")
        self.label_currentTemperature = QtWidgets.QLabel(self.gBoxCurrentTemperature)
        self.label_currentTemperature.setGeometry(QtCore.QRect(20, 50, 301, 41))
        self.label_currentTemperature.setObjectName("label_currentTemperature")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.gBoxCurrentTemperature.setTitle(_translate("Widget", "Current temperature"))
        self.label_currentTemperature.setText(_translate("Widget", "Waiting for the reading..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
